# Site configuration

title: "Welcome to Spress"
description: "A site creted by Spress"

paginate: 5

exclude: ['README.md', 'LICENSE.md']

author:
    name: Your Name
    twitter: '' # Only your username without '@'
