title: "Welcome to Spress"
description: "A site creted by Spress"
logo: spresso-logo.png

url: http://devi-vm.local:8080

# Information about author
author:
    name: Your Name
    
    # Social networks
    twitter: spress_cms
    github: https://github.com/yosymfony/Spress
    facebook:
    gplus: https://google.com/+Yosymfony

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: / }
    
bottom_menu:
    - { name: Go to Spresso theme web, url: https://github.com/yosymfony/Spress-theme-spresso }
    
paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']