title: "Welcome to Spress"
description: "A site creted by Spress"

author:
    name: Your Name
    twitter: spress_cms
    github: https://github.com/yosymfony/Spress
    facebook:
    gplus: https://google.com/+Yosymfony

# Site validation
google_verify:
bing_verify:

# Page menus
top_menu:
    - { name: Home, url: / }
    
bottom_menu:
    - { name: Spresso theme, url: https://github.com/yosymfony/Spress-theme-spresso }
    
paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']