# Site configuration

title: "Welcome to Spress"
description: "A site creted by Spress"

paginate: 5

exclude: ['README.md', 'LICENSE','composer.json']

author:
    name: Your Name

top_menu:
    - { name: Home, url: / }
    
bottom_menu:
    - { name: Spresso theme, url: https://github.com/yosymfony/Spress-theme-spresso }

social_network:
    twitter: # Only your username without '@'
    github:
    facebook:
    gplus:
